# Generated by Django 3.2.19 on 2023-08-22 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person_info',
            name='course',
            field=models.CharField(max_length=20),
        ),
    ]
