# Generated by Django 4.2.4 on 2023-08-25 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0002_alter_person_info_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='person_info',
            name='division',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
