# Generated by Django 4.2.4 on 2023-08-25 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0003_person_info_division'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person_info',
            name='division',
            field=models.CharField(max_length=20),
        ),
    ]
